# Generated by Django 3.2.3 on 2021-06-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('age', models.IntegerField(null=True)),
                ('id_card', models.CharField(max_length=18, null=True)),
                ('tel', models.IntegerField(max_length=13, null=True)),
                ('date', models.DateTimeField()),
                ('card_name', models.CharField(max_length=15, null=True)),
                ('real_type', models.IntegerField(max_length=2)),
                ('password', models.CharField(max_length=15)),
                ('user_type', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
